name: Nick Otto Weddings
favicon: null
layout_spectrum: 0.3665531512815505
typography_spectrum: 0.10316713456995785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.23027791338972747
  lightness: 0.7595226799603552
  saturation: 0.8002920981962234
  rhythmicContrast: 0.6863688074517995
purpose: []
